- hosts: all
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      tags:
        - master

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      tags:
        - master

    - name: join cluster
      shell: "{{ join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
      tags:
        - slave
