- hosts: master
  become: yes
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
  
    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Print return information join command
      debug:
        var: join_command

- hosts: slaves
  become: yes
  gather_facts: yes
  tasks:
    - name: Print return information join command
      debug:
        var: hostvars[groups['master'][0]].join_command

    - name: join cluster
      shell: "{{ hostvars[groups['master'][0]].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
