version: "3"

services:
  poa-blockscout:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    volumes:
      - ./environment:/etc/environment
      - ./docker/entrypoint.sh:/opt/app/entrypoint.sh
    networks:
      - blockscout_network
    depends_on:
      - postgresql

  postgresql:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234qwer
    networks:
      - blockscout_network
    # volumes:
    #     - ./ssl/server.crt:/var/lib/postgresql/ssl/server.crt
    #     - ./ssl/server.key:/var/lib/postgresql/ssl/server.key
    # command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt -c ssl_key_file=/var/lib/postgresql/ssl/server.key

networks:
  blockscout_network:
