scrape_configs:
  - job_name: "openethereum"
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets:
        - "node:3000"
    