- hosts: master
  tasks:
    - name: Copy eth-node
      copy:
        src: ../../../eth-node
        dest: /

    - name: Copy k8s
      copy:
        src: ../../k8s
        dest: /

    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.5.3-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes

    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Install Contour Chart
      kubernetes.core.helm:
        name: my-release
        release_namespace: default
        chart_ref: bitnami/contour

    # Deploy eth node
    - name: Build master node image
      community.docker.docker_image:
        name: eth-master-node
        build:
          path: /eth-node
          dockerfile: ./.docker/node.dockerfile
          args:
            NODE_ID: 0
            JSON_KEY: "{{ JSON_KEY }}"
        source: build

    - name: Deploy master service
      become: yes
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('file', '/k8s/master-service.yml') | from_yaml }}"

    - name: Deploy master node
      become: yes
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('file', '/k8s/master-deployment.yml') | from_yaml }}"

    - name: Deploy master ingress
      become: yes
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('file', '/k8s/master-ingress.yml') | from_yaml }}"
