- hosts: master
  tasks:
    - name: Install python dependencies
      pip:
        name:
          - openshift
          - requests

    - name: Deploy master service
      k8s:
        state: present
        src: "../../k8s/master/master-service.yaml"
        namespace: "default"

    - name: Deploy master node
      k8s:
        state: present
        src: "../../k8s/master/master-deployment.yaml"
        namespace: "default"

    - name: Deploy master ingress
      k8s:
        state: present
        src: "../../k8s/master/master-ingress.yaml"
        namespace: "default"
