- hosts: slaves
  tasks:
    - name: Get master node enode uri
      uri:
        body:
          "method": "parity_enode"
          "params": []
          "id": 1
          "jsonrpc": "2.0"
        body_format: json
        method: POST
        url: "http://{{hostvars[groups['master'][0]]['inventory_hostname']}}:8545/rpc"
        return_content: yes
      register: enode_uri

    - name: Print returned json dictionary
      debug:
        var: enode_uri.json

    - name: Create secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: master-enode-uri
          type: Opaque
          data:
            uri: "{{ enode_uri.json.result | b64encode }}"

    - name: Deploy slave
      k8s:
        state: present
        src: "../../k8s/slaves/slave-deployment.yaml"
        namespace: "default"
