- hosts: slaves
  tasks:
    - name: Get master node enode uri
      uri:
        body:
          "method": "parity_enode"
          "params": []
          "id": 1
          "jsonrpc": "2.0"
        body_format: json
        method: POST
        url: "http://master-service:8545"
        return_content: yes
      register: enode_uri

    - name: Print returned json dictionary
      debug:
        var: enode_uri.json

    - name: Create secret
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: master-enode-uri
          type: Opaque
          data:
            uri: "{{ enode_uri.json.result | b64encode }}"

    #??
    - name: Deploy slave
      community.kubernetes.k8s:
        state: present
        src: /k8s/slave-deployment.yml
