apiVersion: v1
kind: Service
metadata:
  name: master-node-service
spec:
  type: NodePort
  ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
      nodePort: 30545
    - name: "8546"
      port: 8546
      targetPort: 8546
      nodePort: 30546
    - name: "30303"
      port: 30303
      targetPort: 30303
      nodePort: 30303
  selector:
    component: master-node
