- hosts: all
  tasks:
    - name: install kubectl
      apt:
        name: kubectl
        update_cache: true

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
    #- name: Add Helm apt-key
    #  apt_key:
    #    url: https://baltocdn.com/helm/signing.asc
    #    keyring: /usr/share/keyrings/helm-archive-keyring.asc
    #- name: Add Helm apt repository
    #  shell: echo "deb [signed-by=/usr/share/keyrings/helm-archive-keyring.asc] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    #- name: Install Helm
    #  apt:
    #    name: helm
    #    update_cache: true
    #- name: Install contour into k8s
    #  shell: helm repo add bitnami https://charts.bitnami.com/bitnami && helm install my-release bitnami/contour
