version: "3.6"

services:
  node:
    container_name: node${NODE_ID}
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
      args: 
        NODE_ID: ${NODE_ID}
        JSON_KEY: ${JSON_KEY}
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    #  - 9000:9000
    command: "--config /config.toml --nat extip:${NODE_PUBLIC_IP} ${COMMAND_OPTIONS}"
