version: "3.6"

services:
  node:
    image: openethereum/openethereum
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./config.toml:/home/openethereum/config.toml
    command: "--config /home/openethereum/config.toml"
