version: "3.6"

services:
  node:
    container_name: node${NODE_ID}
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
      args: 
        NODE_ID: ${NODE_ID}
        JSON_KEY: ${JSON_KEY}
    ports:
      - ${HTTP_PORT}:8545
      - ${WS_PORT}:8546
    #  - 9000:9000
    command: "--config /config.toml"
    networks: 
      - eth_network

networks:
  eth_network:
    external: true
