apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
        - args:
            - --config
            - /config.toml
            - --nat
            - 'extip:${NODE_PUBLIC_IP}'
            - '${COMMAND_OPTIONS}'
          image: node
          name: node
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 30303
          resources: {}
      restartPolicy: Always
status: {}
