[parity]
# chain = "dev"
chain = "/chainspec.json"
#base_path = "/tmp/parity0"

[mining]
reseal_min_period = 1000
reseal_max_period = 5000
gas_floor_target = "0x165A0BC00"
tx_queue_size = 16384
tx_queue_mem_limit = 4096
tx_queue_per_sender = 16384
engine_signer = "0x12bb164c56ea0f4e90db6774cae98006eae812a1"
reseal_on_txs = "none"

[rpc]
interface = "0.0.0.0"
apis = ["all"]

# shittamask
cors = ["moz-extension://*", "chrome-extension://*"]

[websockets]
interface = "0.0.0.0"
apis = ["all"]

[ipc]
disable = true

[account]
password = ["/home/openethereum/node.pwd"]
