[parity]
# chain = "dev"
chain = "/chainspec.json"
#base_path = "/tmp/parity0"

[mining]
reseal_min_period = 1000
reseal_max_period = 5000
gas_floor_target = "0x165A0BC00"
tx_queue_size = 16384
tx_queue_mem_limit = 4096
tx_queue_per_sender = 16384
engine_signer = "0xc0a5d4d62b43b7e24b67fd556a9d30e62d524370"
reseal_on_txs = "none"

[rpc]
interface = "0.0.0.0"
apis = ["all"]

# shittamask
cors = ["moz-extension://*", "chrome-extension://*"]

[websockets]
interface = "0.0.0.0"
apis = ["all"]

[account]
password = ["/home/openethereum/node.pwd"]

[metrics]
enable = true
interface = "0.0.0.0"
