[parity]
# chain = "dev"
chain = "/home/openethereum/chainspec.json"

[mining]
reseal_on_txs = "all"
reseal_min_period = 1000
reseal_max_period = 5000
gas_floor_target = "0x165A0BC00"
tx_queue_size = 16384
tx_queue_mem_limit = 4096
tx_queue_per_sender = 16384

[rpc]
interface = "0.0.0.0"
apis = ["all"]
# shittamask
cors = ["moz-extension://*"]

[websockets]
interface = "0.0.0.0"
apis = ["all"]

[account]
password = ["/home/openethereum/validator1.key"]
