version: '3.7'

services:
  redis:
    container_name: memento-redis
    image: redis:5.0.5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - .volumes/redis:/data
    networks:
      - node_network

  postgres:
    container_name: memento-postgres
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=memento
      - POSTGRES_DB=memento
      - POSTGRES_PASSWORD=password
    volumes:
      - .volumes/postgresql:/var/lib/postgresql/data
    networks:
      - node_network

  memento:
    container_name: memento
    image: alethio/memento:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 3001:3001
      - 3000:3000
    environment:
      - PG_PASSWORD=password
    volumes:
      - .volumes/memento:/config
    networks:
      - node_network

  explorer:
    container_name: memento-lite-explorer
    image: alethio/ethereum-lite-explorer:latest
    restart: always
    depends_on:
      - memento
      - node
    ports:
      - 80:80
    volumes:
      - .volumes/lite-explorer/config.json:/usr/share/nginx/html/config.json
    networks:
      - node_network

  node:
    image: openethereum/openethereum
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./config.toml:/home/openethereum/config.toml
      - ./chainspec.json:/home/openethereum/chainspec.json
    command: "--config /home/openethereum/config.toml"
    networks:
      - node_network

networks: 
  node_network:
