version: '3.7'

services:
  redis:
    container_name: memento-redis
    image: redis:5.0.5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    # volumes:
    #   - .volumes/redis:/data
    networks:
      - node_network

  postgres:
    container_name: memento-postgres
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=memento
      - POSTGRES_DB=memento
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - node_network

  memento:
    container_name: memento
    image: alethio/memento:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 5000:3000
      - 5001:3001
    environment:
      - PG_PASSWORD=password
    volumes:
      - .volumes/memento:/config:ro
    networks:
      - node_network

  explorer:
    container_name: memento-lite-explorer
    image: alethio/ethereum-lite-explorer:latest
    restart: always
    depends_on:
      - memento
      - node
    ports:
      - 580:80
    volumes:
      - .volumes/lite-explorer/config.json:/usr/share/nginx/html/config.json:ro
    networks:
      - node_network

  node:
    image: openethereum/openethereum
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./config.toml:/home/openethereum/config.toml:ro
      - ./chainspec.json:/home/openethereum/chainspec.json:ro
      - ./validator1.key:/home/openethereum/validator1.key:ro
    command: "--config /home/openethereum/config.toml"
    networks:
      - node_network

networks: 
  node_network:

volumes: 
  postgres_data:
