version: "3"

services:
  poa-blockscout:
    restart: unless-stopped
    build:
      context: ./.docker/app
      dockerfile: app.dockerfile
    environment: 
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASS: "password"
      DATABASE_URL: postgresql://postgres:password@postgres
    ports:
      - "80:4000"
    networks:
      - blockscout_network
    depends_on:
      - postgres

  postgres:
    restart: unless-stopped
    build: 
      context: ./.docker/db
      dockerfile: db.dockerfile
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - blockscout_network
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt -c ssl_key_file=/var/lib/postgresql/ssl/server.key

networks:
  blockscout_network:
